version: "3.8"

services:
  web:
    build:
      context: ./Client/my-app # my-app ke andar Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./Client/my-app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    develop:
      watch:
        - path: ./Client/my-app/package.json
          action: rebuild
        - path: ./Client/my-app/package-lock.json
          action: rebuild

        - path: ./Client/my-app
          target: /app
          action: sync
  api:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      DB_URL: mongodb://db/anime
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

    develop:
      watch:
        - path: ./Client/my-app/package.json
          action: rebuild
        - path: ./Client/my-app/package-lock.json
          action: rebuild

        - path: ./Server
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - anime:/data/db

volumes:
  anime:
