apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-vault-alb-ingress
  namespace: default
  annotations:
    # ALB Setup
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Is se AWS Controller ko pata chalta hai ke ye kis group ka hissa hai
    alb.ingress.kubernetes.io/group.name: media-app-group

    # Ports configuration
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

    # Traffic routing
    kubernetes.io/ingress.class: alb
spec:
  ingressClassName: alb
  rules:
    - host: media-lib.conn-api.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
